[pytest]
# Parámetro para definir los archivos que se van a ejecutar como pruebas. 
#En este caso, se ejecutarán los archivos que comiencen con "test_" y terminen con ".py".
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# -v: Modo detallado
# --html: Genera el reporte visual en formato HTML
addopts = -v --html=report_Final.html --self-contained-html
markers =
    smoke: pruebas criticas del sistema
    regression: pruebas de regresion
    api: pruebas de api
    ui: pruebas de interfaz
